# Generated by Django 5.1 on 2025-10-02 12:15

import django.core.validators
import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('inclass', models.TextField()),
                ('homework', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('pdf_1', models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_2', models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_3', models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_4', models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
