# Generated by Django 5.1 on 2025-10-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='tags',
        ),
    ]
