# Generated by Django 5.1 on 2025-10-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_remove_module_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Module', 'verbose_name_plural': 'Module'},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='terms',
            new_name='tags',
        ),
    ]
