# Generated by Django 5.2.6 on 2026-01-05 19:08

import django.core.validators
import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_module_options_rename_terms_module_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tags',
            new_name='terms',
        ),
        migrations.AlterField(
            model_name='module',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Hausaufgabe'),
        ),
        migrations.AlterField(
            model_name='module',
            name='inclass',
            field=models.TextField(verbose_name='Unterricht'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Skript'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Lösung zum Skript'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Hausaufgabe'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Lösung zur Hausaufgabe'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel des Moduls'),
        ),
    ]
