# Generated by Django 5.2.6 on 2026-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_rename_tags_module_terms_alter_module_homework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
