# Generated by Django 5.2.6 on 2026-01-07 19:16

import django.core.validators
import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='audio_1',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 1'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_2',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 2'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_3',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 3'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_4',
            field=models.FileField(blank=True, null=True, upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 4'),
        ),
    ]
