# Generated by Django 5.2.6 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_module_audio_1_module_audio_2_module_audio_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='audio_1_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titel Audio 1'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_2_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titel Audio 2'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_3_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titel Audio 3'),
        ),
        migrations.AddField(
            model_name='module',
            name='audio_4_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titel Audio 4'),
        ),
    ]
