# Generated by Django 5.2.6 on 2026-01-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_module_audio_1_title_module_audio_2_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_definition', models.CharField(blank=True, max_length=300)),
                ('definition', models.TextField()),
                ('exam_relevant', models.BooleanField(default=False)),
                ('modules', models.ManyToManyField(blank=True, related_name='glossary_terms', to='modules.module')),
            ],
        ),
    ]
