# Generated by Django 5.2.6 on 2026-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_glossaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
