# Generated by Django 5.2.7 on 2026-02-17 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_glossaryentry_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'verbose_name_plural': 'Glossary Entries'},
        ),
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'module'], name='modules_mod_user_id_d5abc0_idx'), models.Index(fields=['user'], name='modules_mod_user_id_e500e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_completion_per_user_module')],
            },
        ),
    ]
