# Generated by Django 5.2.7 on 2026-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_alter_glossaryentry_options_modulecompletion'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagwörter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'verbose_name': 'Lernbegriff', 'verbose_name_plural': 'Lernbegriffe'},
        ),
        migrations.AlterModelOptions(
            name='modulecompletion',
            options={'verbose_name': 'Fortschrittseintrag', 'verbose_name_plural': 'Fortschrittseinträge'},
        ),
        migrations.AlterField(
            model_name='glossaryentry',
            name='exam_relevant',
            field=models.BooleanField(default=False, verbose_name='Prüfungsrelevanz'),
        ),
    ]
