# Generated by Django 5.2.7 on 2026-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_schlagwort_alter_glossaryentry_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schlagwort',
        ),
        migrations.CreateModel(
            name='Aufgabentyp',
            fields=[
            ],
            options={
                'verbose_name': 'Aufgabentyp',
                'verbose_name_plural': 'Aufgabentypen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
    ]
