# Generated by Django 5.2.7 on 2026-02-22 01:56

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_delete_schlagwort_aufgabentyp'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='terms',
        ),
        migrations.AddField(
            model_name='module',
            name='tasktype',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Aufgabentypen'),
        ),
    ]
