# Generated by Django 5.2.6 on 2026-02-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_remove_module_terms_module_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressMatrixProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Fortschritts-Matrix',
                'verbose_name_plural': 'Fortschritts-Matrix',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.modulecompletion',),
        ),
    ]
