# Generated by Django 5.2.6 on 2026-02-26 10:17

import django.core.files.storage
import django.core.validators
import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_progressmatrixproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='audio_1',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 1'),
        ),
        migrations.AlterField(
            model_name='module',
            name='audio_2',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 2'),
        ),
        migrations.AlterField(
            model_name='module',
            name='audio_3',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 3'),
        ),
        migrations.AlterField(
            model_name='module',
            name='audio_4',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Audio Hausaufgabe 4'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Skript'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Lösung zum Skript'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Hausaufgabe'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.module_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Lösung zur Hausaufgabe'),
        ),
    ]
