# Generated by Django 5.2.6 on 2026-03-02 20:33

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modules.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_alter_module_audio_1_alter_module_audio_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressmatrixproxy',
            options={'verbose_name': 'Fortschrittsmatrix', 'verbose_name_plural': 'Fortschrittsmatrix'},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Für reguläre Einheiten 1–40. Für Ferienaufgaben kann es leer bleiben.', null=True, verbose_name='Einheit (1–40)')),
                ('date', models.DateTimeField(db_index=True, help_text='Startzeit der Einheit (wichtig für 36h-Regel).', verbose_name='Datum/Zeit der Einheit')),
                ('kind', models.CharField(choices=[('REGULAR', 'Reguläre Einheit'), ('HOLIDAY', 'Ferienaufgabe'), ('EXAM', 'Prüfung/Check'), ('OTHER', 'Sonstiges')], db_index=True, default='REGULAR', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(blank=True, help_text="Z. B. 'Ferienaufgabe: Intervalle wiederholen' oder 'Klausurvorbereitung'.", max_length=200, verbose_name='Titel (optional)')),
                ('notes', models.TextField(blank=True, help_text='Hier kannst du z. B. Ferien-Aufgabenbeschreibung ablegen, wenn kein Modul verknüpft ist.', verbose_name='Notizen/Anweisungen (optional)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, help_text='Für Ferienaufgaben kann das leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='modules.module', verbose_name='Modul (optional)')),
            ],
            options={
                'verbose_name': 'Unterrichtseinheit',
                'verbose_name_plural': 'Unterrichtseinheiten',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Eingereicht'), ('CORRECTED', 'Korrigiert')], db_index=True, default='SUBMITTED', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Eingereicht am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('note_from_student', models.TextField(blank=True, verbose_name='Notiz (optional)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Schüler/in')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='modules.unit', verbose_name='Einheit')),
            ],
            options={
                'verbose_name': 'Abgabe',
                'verbose_name_plural': 'Abgaben',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/liga/coding-playground/aural-learning-platform/media'), upload_to=modules.models.submission_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Anzeigename (optional)')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reihenfolge')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='modules.submission', verbose_name='Abgabe')),
            ],
            options={
                'verbose_name': 'Abgabe-Datei',
                'verbose_name_plural': 'Abgabe-Dateien',
                'ordering': ['position', 'uploaded_at', 'id'],
                'indexes': [models.Index(fields=['submission', 'uploaded_at'], name='modules_sub_submiss_c748c8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['date'], name='modules_uni_date_16dcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['kind', 'date'], name='modules_uni_kind_35d145_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['number'], name='modules_uni_number_cdfb80_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('number',), name='unique_unit_number_when_set'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'HOLIDAY'), ('number__isnull', True)), models.Q(('kind', 'OTHER'), ('number__isnull', True)), models.Q(('kind', 'EXAM'), ('number__isnull', True)), models.Q(('kind', 'REGULAR'), ('number__isnull', False)), _connector='OR'), name='regular_units_require_number'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['unit', 'status'], name='modules_sub_unit_id_7c1f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='modules_sub_student_28dac8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['unit', 'student'], name='modules_sub_unit_id_3f5e6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('unit', 'student'), name='unique_submission_per_student_unit'),
        ),
    ]
