# Generated by Django 5.2.6 on 2026-03-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_alter_unit_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='module',
            field=models.OneToOneField(blank=True, help_text='Für Ferienaufgaben kann das leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='modules.module', verbose_name='Modul (optional)'),
        ),
    ]
