# Generated by Django 5.2.6 on 2026-03-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_alter_unit_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='submissions_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Abgaben freigeschaltet'),
        ),
    ]
