# Generated by Django 5.2.6 on 2026-03-03 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0022_unit_submissions_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.CreateModel(
            name='UnitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='modules.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unterrichtseinheit abgeschlossen',
                'verbose_name_plural': 'Unterrichtseinheiten abgeschlossen',
                'indexes': [models.Index(fields=['user', 'unit'], name='modules_uni_user_id_824e55_idx'), models.Index(fields=['user'], name='modules_uni_user_id_497262_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'unit'), name='unique_completion_per_user_unit')],
            },
        ),
    ]
