# Generated by Django 5.2.6 on 2026-03-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_alter_module_options_unitcompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitCompletion',
        ),
    ]
