# Generated by Django 5.2.6 on 2026-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
